Repository SAPossible/SAPossible, pull requests merged in 2022-08, with the labels that each got.

#26 [BOJ] G3 17182 "우주 탐사선"
  Soomin-Lee/BOJ_17182_우주-탐사선.py
  Soomin-Lee/BOJ_2174_로봇-시뮬레이션.py
  Soomin-Lee/BOJ_3190_뱀.py
Labels: 백준, 이수민, Gold 3

#27 [BOJ] G5 2174 "로봇 시뮬레이션"
  Hyeji-Kim/BOJ_2174_로봇-시뮬레이션.py
  Hyeji-Kim/BOJ_3190_뱀.java
Labels: 백준, Gold 5, 김혜지

#30 [BOJ] G5 18430 "무기 공학"
  Hyeji-Kim/BOJ_18430_무기-공학.java
Labels: 백준, Gold 5, 김혜지

#31 [BOJ] G4 1976 "여행 가자"
  Soomin-Lee/BOJ_1976_여행-가자.py
Labels: 백준, Gold 4, 이수민

#28 [BOJ] G4 1043 "거짓말"
  Dongwon-Kang/BOJ_1043_거짓말.py
Labels: 백준, Gold 4, 강동원

#32 [BOJ] G515686 "치킨 배달"
  Dongwon-Kang/BOJ_15686_치킨-배달.py
Labels: 백준, Gold 5, 강동원

#29 [BOJ] G4 14502 "연구소"
  Dongwon-Kang/BOJ_14502_연구소.py
Labels: 백준, Gold 4, 강동원
